name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/vectors/search_13_x2.svg
  - assets/vectors/illustration_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/images/doctor_detail.png
  - assets/images/home.png
  - assets/images/top_doctor.png
  - assets/vectors/container_1_x2.svg
  - assets/vectors/vector_17_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/my_logo_x2.svg
  - assets/vectors/vector_16_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/vector_25_x2.svg
  - assets/vectors/vector_33_x2.svg
  - assets/vectors/search_11_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/icon_cognition_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/vector_31_x2.svg
  - assets/vectors/wifi_3_x2.svg
  - assets/vectors/mobile_signal_x2.svg
  - assets/vectors/battery_x2.svg
  - assets/images/screenshot_2_removebg_preview_1.jpeg
  - assets/vectors/vector_x2.svg
  - assets/vectors/wifi_2_x2.svg
  - assets/vectors/mobile_signal_2_x2.svg
  - assets/vectors/battery_1_x2.svg
  - assets/vectors/stroke_12_x2.svg
  - assets/vectors/illustration_1_x2.svg
  - assets/vectors/icon_cognition_2_x2.svg
  - assets/vectors/icon_fluency_1_x2.svg
  - assets/images/screenshot_2_removebg_preview_12.jpeg
  - assets/vectors/vector_27_x2.svg
  - assets/vectors/star_4_x2.svg
  - assets/vectors/ellipse_851_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/vector_29_x2.svg
  - assets/vectors/vector_30_x2.svg
  - assets/vectors/vector_28_x2.svg
  - assets/vectors/vector_32_x2.svg
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/container_2_x2.svg
  - assets/images/screenshot_2_removebg_preview_1.jpeg
  - assets/images/screenshot_2_removebg_preview_13.jpeg
  - assets/images/screenshot_2_removebg_preview_14.jpeg
  - assets/images/screenshot_2_removebg_preview_11.jpeg
  - assets/images/screenshot_2_removebg_preview_12.jpeg
  - assets/vectors/ellipse_85_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/ellipse_855_x2.svg
  - assets/vectors/star_2_x2.svg
  - assets/vectors/wifi_x2.svg
  - assets/vectors/ellipse_853_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/vector_26_x2.svg
  - assets/vectors/battery_2_x2.svg
  - assets/vectors/star_5_x2.svg
  - assets/vectors/vector_19_x2.svg
  - assets/vectors/star_7_x2.svg
  - assets/vectors/star_1_x2.svg
  - assets/vectors/search_12_x2.svg
  - assets/vectors/ellipse_86_x2.svg
  - assets/vectors/mobile_signal_1_x2.svg
  - assets/vectors/star_6_x2.svg
  - assets/vectors/ellipse_856_x2.svg
  - assets/vectors/vector_18_x2.svg
  - assets/vectors/vector_21_x2.svg
  - assets/vectors/object_1_x2.svg
  - assets/vectors/illustration_3_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/images/rectangle_2.jpeg
  - assets/images/screenshot_2_removebg_preview_12.jpeg
  - assets/images/screenshot_2_removebg_preview_1.jpeg
  - assets/vectors/vector_22_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/icon_fluency_x2.svg
  - assets/vectors/ellipse_852_x2.svg
  - assets/vectors/wifi_1_x2.svg
  - assets/vectors/illustration_2_x2.svg
  - assets/vectors/star_x2.svg
  - assets/vectors/mobile_signal_3_x2.svg
  - assets/vectors/battery_3_x2.svg
  - assets/vectors/vector_34_x2.svg
  - assets/vectors/icon_fluency_2_x2.svg
  - assets/vectors/star_3_x2.svg
  - assets/vectors/object_x2.svg
  - assets/vectors/ellipse_854_x2.svg
  - assets/vectors/search_1_x2.svg
  - assets/vectors/vector_20_x2.svg
  - assets/vectors/vector_23_x2.svg
  - assets/vectors/icon_cognition_1_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/vector_24_x2.svg
  - assets/vectors/object_2_x2.svg

